spring.application.name=apiData

spring.datasource.url=jdbc:postgresql://localhost:5432/evasao
spring.datasource.username=postgres
spring.datasource.password=luizsql@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true